# model_name: "google/vit-base-patch16-224" 
# output_dir: "model_base-patch16_epoch10_lr1e-4"  

model_name: "google/vit-large-patch32-384" 
output_dir: "model_large-patch32_epoch10_lr5e-5"  

num_labels: 3  

train_csv: "dataset/train_data.csv"  
test_csv: "dataset/test_data.csv"
train_ratio: 0.8  
class_names: ["spaghetti", "ramen", "udon"]

batch_size: 32
num_train_epochs: 10
weight_decay: 0.01
logging_steps: 10
label_smoothing_factor: 0.1  
fp16: false

learning_rate: 5e-5 # 1e-4
classifier_lr: 3e-4  
encoder_lr: 3e-5    

lr_scheduler_type: "cosine"  
warmup_ratio: 0.1            